version: "3"
services:
  reverseproxy:
    build:
      context: ../../reverseproxy
    image: arustle/psa-reverseproxy 
  backend_user:
    build:
      context: ../../restapi-user
    image: arustle/psa-restapi-user
  backend_feed:
    build:
      context: ../../restapi-feed  
    image: arustle/psa-restapi-feed
  frontend:
    build:
      context: ../../frontend  
    image: arustle/frontend:local
